apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: hcl-hackathon
        image: docker.io/abhishekrampati/order-service:latest  # Replace with your Docker image path
        ports:
        - containerPort: 8080
