apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080     # Service port inside cluster
      targetPort: 8080  # Container port on the pod
      nodePort: 30082   # NodePort (must be in 30000–32767)