apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: hcl-hackathon
        image: docker.io/abhishekrampati/patient-service:latest  # Replace with your Docker image path
        ports:
        - containerPort: 3001
